(() => {
const URL='https://tasoycsbzceohgjxizdp.supabase.co';
const KEY='sb_publishable_ZLU-d0ZI-XT_IgabzmigkA_5vohKjLl';
const ENDPOINT=`${URL}/functions/v1/credence-checkout`;
const token=()=>{try{return JSON.parse(localStorage.getItem('credence_session')||'null')?.access_token||''}catch{return ''}};
const originalFetch=window.fetch.bind(window);
window.fetch=(input,init)=>{try{const u=typeof input==='string'?input:input?.url||'';if(u.startsWith(`${URL}/auth/v1/signup?`)){const x=new URL(u);x.searchParams.set('redirect_to',`${URL}/functions/v1/credence-confirmation`);return originalFetch(x.toString(),init)}}catch{}return originalFetch(input,init)};
const syncJoinButton=()=>{const b=document.getElementById('heroLogin'),d=document.getElementById('dashboard');if(!b)return;let logged=false;try{logged=!!JSON.parse(localStorage.getItem('credence_session')||'null')?.access_token}catch{}b.classList.toggle('hidden',logged&&!d?.classList.contains('hidden'))};
function notice(text,good=false){const n=document.getElementById('checkoutNotice');if(n){n.innerHTML=text;n.classList.remove('hidden');n.style.borderColor=good?'#b7e4c7':'#ffd6a5';n.style.background=good?'#f0fff4':'#fff8ed'}}
async function loadRazorpay(){if(window.Razorpay)return true;return await new Promise(resolve=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
function goLearning(message){document.getElementById('courseModal').hidden=true;window.CREDENCE_LEARNING?.load();document.getElementById('dashboard')?.classList.remove('hidden');document.getElementById('myLearningGrid')?.scrollIntoView({behavior:'smooth',block:'start'});alert(message)}
async function checkout(courseId,btn){const t=token();if(!t){document.getElementById('loginBtn')?.click();return}if(!courseId)throw Error('Course could not be identified');if(btn){btn.disabled=true;btn.textContent='Preparing…'}try{
 const d=await api({action:'create_order',course_id:courseId});
 if(d.status==='already_enrolled'||d.status==='enrolled'){goLearning('You are enrolled. Start learning! 🎓');return}
 if(d.status==='payment_setup_required'){notice('<b>Razorpay Test Mode is not configured yet.</b><br>Add the three Razorpay secrets privately in Supabase. No enrollment is created.');return}
 if(d.status!=='order_created'||!d.razorpay_order_id||!d.key_id||!d.amount)throw Error(d.error||'Unable to create payment order');
 const ready=await loadRazorpay();if(!ready)throw Error('Payment checkout could not load. Check your internet connection and try again.');
 notice('<b>Secure checkout ready.</b><br>Choose UPI in Razorpay Checkout. Test Mode uses simulated payments; no real money is charged.');
 let profile={};try{profile=JSON.parse(localStorage.getItem('credence_profile')||'null')||{}}catch{}
 const options={key:d.key_id,amount:d.amount,currency:d.currency||'INR',name:'CREDENCE',description:d.course?.title||'CREDENCE Course',order_id:d.razorpay_order_id,prefill:{name:profile.full_name||'',email:profile.email||''},theme:{color:'#08783f'},handler:async response=>{try{notice('<b>Verifying payment…</b><br>Please wait. Course access is granted only after server verification.');const v=await api({action:'verify_payment',order_id:d.order_id,razorpay_order_id:response.razorpay_order_id,razorpay_payment_id:response.razorpay_payment_id,razorpay_signature:response.razorpay_signature});if(v.status!=='enrolled')throw Error(v.error||'Payment was not verified');goLearning('Payment verified — you are enrolled! 🎓')}catch(e){notice(`<b>Payment verification failed.</b><br>${String(e.message||'Please contact CREDENCE support.').replace(/[<>]/g,'')}`)}},modal:{ondismiss:()=>notice('<b>Payment cancelled.</b><br>No course access was granted.')}};
 const rzp=new Razorpay(options);rzp.on('payment.failed',r=>notice(`<b>Payment failed.</b><br>${String(r?.error?.description||'Please try again.').replace(/[<>]/g,'')}`));rzp.open();
 }catch(e){notice(`<b>Checkout unavailable.</b><br>${String(e.message||'Please try again.').replace(/[<>]/g,'')}`)}finally{if(btn){btn.disabled=false;btn.textContent='Buy / Enroll'}}}
async function inject(){const modal=document.getElementById('courseModal'),body=document.getElementById('modalBody');if(!modal||modal.hidden||!body||document.getElementById('credenceBuy'))return;const courseId=modal.dataset.courseId;if(!courseId)return;const r=await originalFetch(`${URL}/rest/v1/courses?select=id,title&published=eq.true&id=eq.${encodeURIComponent(courseId)}&limit=1`,{headers:{apikey:KEY}});if(!r.ok)return;const rows=await r.json();if(!rows[0]||document.getElementById('credenceBuy'))return;const wrap=document.createElement('div');wrap.className='actions';wrap.innerHTML='<button id="credenceBuy">Buy / Enroll</button><div id="checkoutNotice" class="notice hidden"></div>';body.insertBefore(wrap,body.children[1]||body.firstChild);document.getElementById('credenceBuy').onclick=()=>checkout(courseId,document.getElementById('credenceBuy'))}
window.CREDENCE_CHECKOUT={checkout};new MutationObserver(()=>{inject();syncJoinButton()}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['hidden','data-course-id','class']});document.addEventListener('DOMContentLoaded',()=>{inject();syncJoinButton();setTimeout(syncJoinButton,500)});
})();